import { writable } from "svelte/store";
export const debtors = writable([]);
export const token = writable("");
export const isAuthenticated = writable(false);
export const user = writable({});
export const popupOpen = writable(false);
export const error = writable();
export const messageToUser = writable("");
export const loadersCount = writable(-1);
export const isOnline = writable(true);
